import React from "react";
import { Link } from "react-router-dom";

const PrivacyPolicy = () => {
  return (
    <>
      <div
        className="modal fade"
        tabIndex="-1"
        role="dialog"
        id="modal-cookies"
        data-backdrop="false"
        aria-labelledby="modal-cookies"
        aria-hidden="true"
      >
        <div className="modal-dialog modal-dialog-aside left-4 right-4 bottom-4">
          <div className="modal-content bg-dark-dark">
            <div className="modal-body">
              <p className="text-sm text-white mb-3">
                We use cookies so that our themes work for you. By using our
                website, you agree to our use of cookies.
              </p>

              <a
                href="pages/utility/terms.html"
                className="btn btn-sm btn-white"
                target="_blank"
              >
                Learn more
              </a>
              <button
                type="button"
                className="btn btn-sm btn-primary mr-2"
                data-dismiss="modal"
              >
                OK
              </button>
            </div>
          </div>
        </div>
      </div>
      <nav className="navbar navbar-expand-lg navbar-light bg-white">
        <div className="container">
          <a className="navbar-brand" href="/">
            <span>
              <h3>
                <span style={{ color: "#7ac81e" }}>JLE </span>Megamart
              </h3>
            </span>
          </a>

          <div className="collapse navbar-collapse" id="navbarCollapse">
            <ul className="navbar-nav mt-4 mt-lg-0 ml-auto"></ul>

            <Link
              className="navbar-btn btn btn-sm btn-primary d-none d-lg-inline-block ml-3"
              to="/login"
            >
              Sign In
            </Link>

            <div className="d-lg-none text-center">
              <a href="#" className="btn btn-block btn-sm btn-warning">
                See more details
              </a>
            </div>
          </div>
        </div>
      </nav>
      <h1>introduction</h1>
      <p>
        Jle mega mart is committed to protecting your privacy. The purpose of
        this Privacy Policy (hereinafter referred to as ‘Policy’) is to inform
        you as to what information may be collected from you when you visit our
        website, including all pages within this website, content platforms,
        applications (collectively referred to herein below as this “Website”)
        or when you become a Distributor, how such information will be used by
        Jle mega mart and / or other persons or entities, with whom such
        information may be shared, your choices regarding the collection, use
        and distribution of such information, your ability to edit, update,
        correct or delete such information and the security procedures that we
        have implemented to protect your privacy.
      </p>
      <p>
        This Privacy Policy applies to all personal information collected by Jle
        mega mart during the course of any usage of the service provided. By
        using the service, the you agree to comply with Jle mega mart’s
        policies. This Privacy Policy is embedded in an electronic format under
        the Information Technology Act, 2000 and the Rules made thereunder and
        the amendments regarding electronic documents as amended by the said
        Act. This document is an electronic record generated by a computer
        system and does not require any physical or digital signatures.
      </p>
      <h1>I. NOTICE for Collection of Information:</h1>
      <p>
        This notice applies to anyone who interacts with us in relation to our
        products and services, by any mode of communication. We may give you
        additional privacy notices if required for specific interactions.
      </p>
      <p>
        You may be asked for certain types of personal information (e.g., your
        first and last name, PAN, mailing address, city, state, Pincode,
        telephone number, email address, credit card number, bank information,
        etc.). If you do not want to disclose your personal information to us,
        please do not submit it. This does mean that in some cases, we may not
        be able to provide you the service you have requested. Your personal
        information is used for efficient service and better user experience on
        the Website.
      </p>
      <p>
        Jle mega mart may also collect Miscellaneous Information through your
        interaction with and use of the Website which does not reveal your
        specific identity or does not directly relate to an individual/entity.
        Miscellaneous Information may include, but is not limited to, browser
        and device information, data collected through automated electronic
        interactions, application usage data, demographic information,
        geographic or geo-location information, statistical and aggregated
        information. In some instances, Jle mega mart may combine Miscellaneous
        Information with Personal Information, such as combining a precise
        geographical location with ADN. In such cases, combined information will
        be treated as your personal information.
      </p>
      laws.
      <h1>II. Use of Information:</h1>
      <p>
        We will keep your personal information private. You will be informed
        about these purposes at various parts of the Direct Seller Agreement,
        Jle mega mart Policies & Procedures, Jle mega mart Compensation Plan,
        Jle mega mart Code of Ethics (hereinafter collectively referred to as
        ‘Agreement’) as well as on the Website of the Company. For instance,
        information about Distributors will be used to provide services,
        calculate earnings and bonuses, and ensure compliance with the company’s
        regulations. In compliance and requirements to maintain records, the
        Company may need personal information for confirmation and reporting
        commissions, withholding & reporting applicable taxes.
      </p>
      <p>
        It may also be used to set up, generate & administer ADN, provide
        necessary technical support, verify identify of the Direct
        Seller/Website user and send important communication.
      </p>
      <p>
        It may also be used to deliver marketing and event-based communication.
        We also use technology to help us understand your personal preferences
        and interests so that we can send recommendations and marketing
        communications that are likely to be of more interest to you.
      </p>
      <p>
        It may also be used for internal research and development purposes and
        to improve and test the features and functions of the Website.
      </p>
      <p>
        Jle mega mart may use and retain personal information for legal and
        compliance reasons, such as the prevention, detection, or investigation
        of a crime; loss prevention; or fraud, or to meet our internal and
        external audit requirements, information security purposes, and/or which
        is required: (a) under applicable law (b) to respond to requests from
        courts, law enforcement agencies, regulatory agencies, and other public
        and government authorities, (c) to be shared with vendors to perform
        functions on our behalf, such as fulfilling orders, delivering packages,
        processing payments, and providing customer service or Websites that
        integrate with our API or services, or those with an API or service with
        which we integrate. These vendors are under a contractual obligation to
        use confidential data received from Jle mega mart only for purposes that
        fall within the functions for which they were hired. (d) to enforce Jle
        mega mart’s Agreement; and (e) to protect Jle mega mart’s rights,
        privacy, safety, or property, or those of other persons.
      </p>
      <h1>III. Use of Cookies:</h1>
      <p>
        Cookies are small pieces of information that are stored on computer hard
        drives. We may use cookies to recognize you when you return to the
        Website in order to provide you with a better user experience. We may
        allow third parties to use cookies on the Website.
      </p>
      <p>
        We do not control the use or contents of third party cookies. If you
        elect to block cookies, please note that you may not be able to take
        full advantage of the features and functions of the Website.
      </p>
      <p>
        You may accept or decline the cookies when you access the Website. It is
        your responsibility to set your browser to alert you to accept or to
        reject cookies.
      </p>
      <h1>IV. Data Transmission & Information security:</h1>
      <p>
        We take reasonable steps to ensure that the personal information we
        collect about you remains accurate, timely and secure. Unfortunately, no
        data transmission over the Internet can be guaranteed to be 100% secure
        and while we strive to protect your personal information, we cannot
        guarantee or warrant its complete security. We shall not be responsible
        for harm that you or any person may suffer as a result of a breach of
        confidentiality in respect to your use of the Website or any information
        you transmit to the Website.
      </p>
      <p>
        When you use Jle mega mart’s Website, you agree and understand that you
        are communicating with Jle mega mart through electronic means and you
        give your explicit consent to receive communications via electronic
        means from Jle mega mart periodically and as and when required. It is
        however to be noted that Jle mega mart may communicate with you by any
        of the means such as email, Website Notifications, alerts or by such
        other mode of communication, electronic or otherwise.
      </p>
      <p>
        You specifically agree that Jle mega mart shall not be held responsible
        for unauthorized access to or alteration of your transmissions or data,
        any material or data sent or received or not sent or not received.
        Further, Jle mega mart will make best efforts to safeguard the
        confidentiality of your personally identifiable information available
        with it, but transmissions made by means of the internet cannot be
        guaranteed or made absolutely secure. By using this Website, you agree
        that Jle mega mart shall not be liable for disclosure of your
        information due to errors in transmission or unauthorized acts of third
        parties. Without prejudice to the foregoing you agree that Jle mega mart
        shall not be held liable or responsible for 'phishing attacks' or such
        other similar attacks on you.
      </p>
      <h1>V. username(ID) & Password Management:</h1>
      <p>
        {" "}
        Jle mega mart will not be held liable for any problems caused by the
        misuse of USENAME(ID) and password or the use of others. Under no
        circumstances should you tell anyone your password and take special care
        not to leak your personal information to others around you while logged
        on. If the Distributorship or purchase is confirmed by stealing other
        people's personal information, the Agreement can be terminated
        unilaterally. Please contact Jle mega mart immediately in case you
        believe that your Password has been misused.
      </p>
      <h1>VI. Use of Vendors:</h1>
      <p>
        We may employ vendors to perform functions on our behalf, such as
        fulfilling orders, delivering packages, processing payments, and
        providing customer service. These vendors are under a contractual
        obligation to use confidential data received from Jle mega mart only for
        purposes that fall within the functions for which they were hired.
      </p>
      <p>
        We may disclose information that we collect about you when we have
        reason to believe that this is necessary to identify, contact or bring
        legal action against persons or entities that may be harming you, us or
        others. We may also disclose information when we believe the law
        requires it.
      </p>
      <h1>VII. Transfer of information:</h1>
      <p>
        You hereby acknowledge & accept that the information you provide to us
        or that we obtain as a result of your use of the Website may be
        collected in your country and subsequently transferred to another
        country in accordance with applicable laws. If you do not want to
        disclose your personal information to us, please do not submit it. This
        does mean that in some cases, we may not be able to provide you the
        service you have requested. The use of this Website & the provision of
        information from your side demonstrates your consent to the processing
        of information as described in these Terms.
      </p>
      <h1>VIII. Modifications, Amendments & Changes to the Policy: </h1>
      <p>
        Jle mega mart reserves the right to modify this Policy at any time at
        its sole and absolute discretion without any obligation of issuing
        notification to the users of the Website. It will be your responsibility
        to keep yourself updated with the Policy from time to time. Your
        continued usage of Jle mega mart Website and services would be deemed to
        be an acceptance of these terms and the modifications thereto.
      </p>
      <h1>IX. Complaints & Suggestions:</h1>
      <p>
        If you have any questions, comments, complaints or suggestions in
        relation to this notice, or any other concerns about the way in which we
        process information about you, please contact us by sending an email to
        Customer Care or through the Website.
      </p>
      <footer className="position-relative" id="footer-main">
        <div className="footer pt-lg-7 footer-dark bg-dark">
          <div className="shape-container shape-line shape-position-top shape-orientation-inverse">
            <svg
              width="2560px"
              height="100px"
              xmlns="http://www.w3.org/2000/svg"
              preserveAspectRatio="none"
              x="0px"
              y="0px"
              viewBox="0 0 2560 100"
              className="fill-section-secondary"
            >
              <polygon points="2560 0 2560 100 0 100"></polygon>
            </svg>
          </div>

          <div className="container pt-4">
            <div className="row">
              <div className="col-lg-4 mb-5 mb-lg-0">
                <a href="index.html">
                  {/* <!-- <img alt="Image placeholder" src="assets/img/brand/logo.png" id="footer-logo"> --> */}
                  <span>
                    <h3 style={{ color: "white" }}>
                      <span style={{ color: "#7ac81e" }}>JLE </span>Megamart
                    </h3>
                  </span>
                </a>

                <p className="mt-4 text-sm opacity-8 pr-lg-4">
                  JLE is an attempt to give tier 2 city the feel of e-commerce.
                </p>

                <ul className="nav mt-4">
                  <li className="nav-item">
                    <a className="nav-link" href="#" target="_blank">
                      <i className="fab fa-instagram"></i>
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#" target="_blank">
                      <i className="fab fa-facebook"></i>
                    </a>
                  </li>
                </ul>
              </div>

              <div className="col-lg-2 col-6 col-sm-4 ml-lg-auto mb-5 mb-lg-0"></div>
              <div className="col-lg-2 col-6 col-sm-4 mb-5 mb-lg-0"></div>
              <div className="col-lg-2 col-6 col-sm-4 mb-5 mb-lg-0"></div>
            </div>
            <hr className="divider divider-fade divider-dark my-4" />
            <div className="row align-items-center justify-content-md-between pb-4">
              <div className="col-md-6">
                <div className="copyright text-sm font-weight-bold text-center text-md-left">
                  &copy; 2022{" "}
                  <a href="#" className="font-weight-bold" target="_blank">
                    JLE Megamart
                  </a>
                  . All rights reserved
                </div>
              </div>
              <div className="col-md-6">
                <ul className="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
                  <li className="nav-item">
                    <Link className="nav-link" to="/terms-and-conditions">
                      Terms
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/privacy-policy">
                      Privacy
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/refund">
                      Refund
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/contact-us">
                      Contact Us
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" to="/about-us">
                      About Us
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </footer>
    </>
  );
};

export default PrivacyPolicy;
