import React from 'react';
import {Link} from 'react-router-dom'

const TermsAndConditions = () => {

          return (
                    <>
                    <div className="modal fade" tabIndex="-1" role="dialog" id="modal-cookies" data-backdrop="false" aria-labelledby="modal-cookies" aria-hidden="true">
        <div className="modal-dialog modal-dialog-aside left-4 right-4 bottom-4">
            <div className="modal-content bg-dark-dark">
                <div className="modal-body">
  
                    <p className="text-sm text-white mb-3">
                        We use cookies so that our themes work for you. By using our website, you agree to our use of cookies.
                    </p>
                   
                    <a href="pages/utility/terms.html" className="btn btn-sm btn-white" target="_blank">Learn more</a>
                    <button type="button" className="btn btn-sm btn-primary mr-2" data-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>
   
    <nav className="navbar navbar-expand-lg navbar-light bg-white">
        <div className="container">

            <a className="navbar-brand" href="/">
                <span><h3><span style={{color : '#7ac81e'}}>JLE </span>Megamart</h3></span>
                {/* <!-- <img alt="Image placeholder" src="assets/img/brand/logo.png" id="navbar-logo"> --> */}
            </a>
           
            {/* <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span className="navbar-toggler-icon"></span>
            </button> */}
           
            <div className="collapse navbar-collapse" id="navbarCollapse">
                <ul className="navbar-nav mt-4 mt-lg-0 ml-auto"></ul>
               
                <Link className="navbar-btn btn btn-sm btn-primary d-none d-lg-inline-block ml-3" to="/login">
                    Sign In
                </Link>
              
                <div className="d-lg-none text-center">
                    <a href="#" className="btn btn-block btn-sm btn-warning">See more details</a>
                </div>
            </div>
        </div>
    </nav>
 
     <h1>A. Introduction</h1>
     <p>These Website Terms and Conditions (hereinafter referred to as “Terms/Terms of Use”) contained herein on this webpage, shall govern your use of this website, including all pages within this website, content platforms, applications (collectively referred to herein below as this “Website”). They apply to Jle mega mart’s provision and your use of Jle mega mart’s content platforms, sites, applications and services. Your access to the services is permitted by Jle mega mart on the basis that you have accepted these terms, and in consideration for that acceptance. If you do not agree to the terms, you are not permitted to access the services in any manner. You must not use this Website in any way, if you have any objection to any of these Terms. If you do access the services (whether you make use of them or not), you are deemed to have agreed to these Terms in their entirety. Your agreement with Jle mega mart includes any specific additional terms and policies that apply to any specific services that you use.</p>
     <p>Please read these terms carefully before accessing, using, obtaining or availing any products or services by Jle mega mart. If you do not agree with these Terms of Use you may refrain from using Jle mega mart’s Website and/or services. These conditions must be read in conjunction with any other applicable terms and conditions governing the use of Jle mega mart Website and services.</p>
     <p>Downloading, installing, browsing or otherwise using Jle mega mart’s Website signifies acceptance of these Terms of Use as well as agreement to be legally bound by the same.</p>
     <p>This document is an electronic record generated by a computer system and does not require any physical or digital signatures.</p>
     <h1>B. Modifications, Amendments & Changes to the Terms: </h1>
<p>Jle mega mart reserves the right to modify these Terms of Use at any time at its sole and absolute discretion without any obligation of issuing notification to the users of the Website. It will be your responsibility to keep yourself updated with the Terms of Use from time to time. Your continued usage of Jle mega mart Website and services would be deemed to be an acceptance of these terms and the modifications thereto.</p>
<h1>C. Eligibility to Use:</h1>
<p>You must be at least eighteen (18) years of age or above and capable of entering, performing and adhering to these terms. While individuals under the age of 18 may utilize/browse the Website, they shall do so only with the involvement, guidance and supervision of their parents and / or legal guardians, under such parent /legal guardian’s registered account. Jle mega mart reserves the right to terminate User’s access and refuse to provide User with access to the Website if Jle mega mart discovers that User is under the age of 18 years.</p>
<p>You hereby acknowledge & agree that you are fully able and competent, as has been defined under the provisions of the Indian Contract Act, 1872, to understand and agree the terms, conditions, obligations, affirmations, representations and warranties set forth in these Terms of Use. Persons who are incompetent to contract within the meaning of Indian Contract Act, 1872 including minors, insolvents etc. are not eligible to use the Website. Any visit or use of the Website shall be treated as representation of being competent to enter into a contract.</p>
<p>It may be noted that the Website is a general audience Website that is not specifically designed or targeted at children. We do not knowingly collect, use or disseminate any personal information from persons under the age of 18. If, however, we become aware that personal information regarding a person under the age of 18 has been collected at the Website, we will make reasonable efforts to delete it from our records.</p>

<h1>D. Using Website:</h1>
<p>To use various parts of the Website you will have to first create an account by following the instructions given below;
Detailed procedure for becoming Jle mega mart Direct seller in the case of individuals has been provided below:
Step 1: Login with Guest Credentials of the Sponsor
Step 2: View Jle mega mart Orientation Videos
Step 3: Read Direct Seller Agreement, Code of Ethics and Principles, Jle mega mart’s Policies and Procedures and Jle mega mart Compensation Plan. Provide consent abiding by the contents, terms and conditions.
Step 4: Fill personal information
Step 5: Upload Address proof document (Both Front & Back Page)
Step 6: Auto PAN verification is done; Direct Seller name gets populated per PAN
Step 7: Partner to provide Spouse Information
Step 8: Sponsor details to be filled
Step 9: After filling all the details in the direct seller application, electronic record will be generated which doesn’t require digital/physical signature and it binds both the parties as per applicable law
Step 10: Jle mega mart Distributor Number (id) & Password is generated and registration Complete</p>
<h1>E. Website Availability:</h1>
<p> Jle mega mart does not guarantee that the Website, products or services will always be available, work, or be accessible at any particular time. Further, only users who are eligible to use our services may do so and Jle mega mart reserves the right to limit access to or terminate the service and agreement of anyone without limitation.</p>
<h1>F. No Warranties:</h1>
1.	<p>i. The services on the Website are provided on an "as is" basis without warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose.
2.	ii. Nothing contained on this website shall be construed as providing consult or advice to you.
3.	iii. Jle mega mart makes no warranty that:
• Jle mega mart’s Website or the services will meet your requirements or your use of the Website or that it will be uninterrupted, timely, secure or error-free.
• The results that may be obtained from the use of the Website, or Services will be effective, accurate or reliable.
• The quality of the Website, or services will meet your expectations
• Any errors or defects in the Website or services will be corrected</p>
<h1>Information Disclaimer</h1>
<p>The Website user agrees that:</p>
<h1>Information Reliance</h1>
<p>All information supplied has NO WARRANTY whatsoever. Information and statements are not intended to diagnose, treat, improve, benefit, cure, or prevent any disease, medical condition, or health concern or physical goals. No warranty is made that any information on or linked to the Website is complete and/or accurate. All information contained on Jle mega mart’s website, including information relating to medical and health conditions, products and treatments, is for informational purposes only. It is often presented in summary or aggregate form and must be purchased and used or consumed in consultation with medical or professional heath care advice.</p>
<h1>Must Seek Advice</h1>
<p>Professional advice is required for each particular illness, disease, infection, injury or other medical or health condition and for dosages or usage instructions in relation to any health-related product or service made available for sale on the Website. This information is not to be taken as any sort of medical advice whatsoever, and the Distributor/Website User takes full and total responsibility for what he/she/it does with this information, and any resulting outcomes from his/her/its actions. They must also consult with their physical health care provider prior to the purchase and use of any of Jle mega mart products or services available on the Website.</p>
<h1>No Substitute for Advice</h1>
<p>The information contained in this Website is not intended nor is it implied to be a substitute for professional medical or health advice or any information contained on or in any product packaging or labels. Always seek the advice of your Pharmacist, General Practitioner, other Medical practitioner or qualified health care provider when starting any new medical treatment, dietary plan, dietary consumption, usage of product, physical exercise or activity, continuing with medical treatment or with any questions you may have regarding yours or any other parties medical or physical condition.
NOTHING CONTAINED IN THE WEBSITE IS INTENDED TO BE OR SHOULD BE TAKEN FOR MEDICAL DIAGNOSIS OR TREATMENT OR HEALTH AND WELL BEING ADVICE OR INFORMATION OR THAT THE USAGE OF PRODUCTS AVAILABLE ON Jle mega mart’S WEBSITE ARE SAFE FOR YOUR PERSONAL USE.
The user should carefully read and strictly follow all product labels, packaging inserts, instructions, directions and cautions provided by Jle mega mart or the Manufacturer/Brand owner, as the case may be, before using any product. It is the sole responsibility of the user to follow the instructions & evaluate the ingredients in order to avoid allergic reactions or other side effects personal to them.</p>
<h1>No Guarantee of </h1>
<p>Jle mega mart does not guarantee that any specific or beneficial result will be obtained from use of the Jle mega mart services, purchase of Jle mega mart products, or promotion or referral of customers to become Direct Sellers and purchase Jle mega mart products.</p>
<h1>Action by You</h1>
<p>If you notice any adverse, detrimental, negative or concerning changes to your physical, mental or emotional health upon accessing Jle mega mart services and products, you will seek the attention of your independent health care professional immediately.</p>
<h1>Testimonials</h1>
<p>Any testimonials displayed on the Website may not reflect the results that you may achieve. Results may vary and your experience may not be similar to the experience of the user testimonials.</p>
<h1>Acceptance of Risk</h1>
<p>You acknowledge and accept that the purchase and use of the Jle mega mart products and services may expose you to risk of physical harm when used or consumed. You purchase and use the product having considered and accepted the potential risks and are responsible for any adverse consequences that may occur.</p>
<h1>G. Intellectual Property:</h1>
<p>Meaning of Intellectual Property: Intellectual Property means all copyright, trade mark rights, logo, patent rights, design rights or any other Intellectual Property Rights subsisting in or created during the development of the products, Jle mega mart Website, Jle mega mart business, and the Trade Marks and any advertising and promotional materials provided to the Website user including software, Confidential Information, source and object codes, scripts, records, documents, advertising and promotional materials, media content, specifications, plans, program listings, calculations, drawings, technology, business names, commercial symbols, processes, developments, licenses, trade secrets, techniques, specifications, patterns, drawings, formulae, technical information, research data, concepts, methods, procedures, reports, recommendations and any other knowledge of any nature whatsoever including patents, copyrights, trademarks, trade names, design and any amendments/modifications, renewals thereto and all Confidential Information necessary for, or which may be used in connection with the administration, operation and marketing of the Jle mega mart products and services
1.	• The Website user agrees that all rights in and relating to the Intellectual Property are and remain the property or under the control of Jle mega mart and that such user does not acquire any right, title or interest in any of the Intellectual Property.
2.	• This site is owned and operated by Jle mega mart. Unless otherwise specified, all material appearing on this site, including the text, site design, logos, graphics, icons and images, photographs, graphics, typefaces and other material (collectively "Content") as well as the selection, assembly and arrangement thereof is subject to applicable laws.
3.	• All audio and video clips are the sole property of Jle mega mart or their respective content providers. All software used on the site is the sole property of Jle mega mart or those supplying the software. You acknowledge that the Website contains content, audio and video clips and software that are protected by copyrights, trademarks, or other intellectual property rights, and that these rights are valid and maybe protected in all forms, media and technologies which exist now or are developed in the future. You may use the content of this Website only for the purpose of shopping on this site or placing an order on this site and for no other purpose. No materials from this site may be copied, reproduced, modified, republished, uploaded, posted, transmitted, or distributed in any form or by any means without Jle mega mart’s prior expressed written authorization. All rights not expressly granted herein are reserved. Any unauthorized use of the materials appearing on this site may violate copyright, trade mark and other applicable laws and could result in criminal or civil penalties.
4.	• The Website user agrees that any feedback, comments, ideas, suggestions, information, or any other content which the Website user contributes to Jle mega mart will be deemed to include a royalty-free, perpetual, irrevocable, non-exclusive right and license for Jle mega mart to adopt, publish, reproduce, disseminate, transmit, distribute, copy, use, create derivative works from, display worldwide, or act on such content without additional approval or consideration in any form, media, or technology now known or later developed for the full term of any rights that may exist in such content, and you waive any claim to the contrary. The Website user represents and warrants that he/she/it owns or otherwise controls all of the rights to the content that he/she may contribute to this Website and that use of his/her/its content by Jle mega mart shall not infringe upon or violate the rights of any third party.
Meaning of Confidential Information: For the purposes of these Terms of Use, the term “Confidential Information” shall include any information or data of a scientific, technical, commercial or financial nature disclosed by Jle mega mart, or which is obtained by Direct Seller from Jle mega mart whether in writing, pictorially, in machine readable form, on disc, mail or orally, or by any other means/modes of disclosure and including without limitation any information contained in any written or printed document, hardware, firmware and software, Website, information related to technology and business activities (including, but not limited to, communication systems, business outlooks, revenue, pricing, trade secrets), computer programs, software (including, without limitation, code, software output, screen displays, file hierarchies and user interfaces), formulas, data, inventions, techniques, technology, know-how, processes, ideas, (whether patentable or not), schematics, specifications, drawings, product designs, product plans, pricing, services, strategies, third party confidential information, and corporate and personnel statistics, customer lists (potential or actual) and other customer-related information, supplier information, sales statistics, market intelligence, marketing, business working , operations, parent, subsidiaries, affiliates downline report provided or accessible to a Direct Seller, manufacturer information, Commission or sales reports, Product formulas, other financial and business information of Jle mega mart and other business strategies and other commercial information of confidential nature or such information that by its inherent nature is confidential or proprietary.</p>
<h1>H. Restrictions on the use of the Website:</h1>
<p>Certain parts of this website may be restricted from access to you and Jle mega mart may further restrict access to you to any areas of this website, at any time, in its sole and absolute discretion. Username(id) and password you have for this Website are confidential and you must maintain confidentiality of such information.
Any content which is misleading, obscene, indecent, pornographic or sexually suggestive in nature, constitutes a direct attack against an individual or group, promotes violence, is highly discriminatory in nature or constitutes spamming or creating fake user’s will be removed from the Website &/or Jle mega mart’s database without any intimation in respect thereof.
In addition to what has been stated above, the Distributor/Website User must:
1.	i. not register or seek to register any of the Intellectual Property without the prior written consent of Jle mega mart;
2.	ii. not cause any of the Intellectual Property to be prejudicially affected or contested;
3.	iii. not use the Intellectual Property without the prior express written authority of Jle mega mart & in terms of the Agreement between the Direct Seller & Jle mega mart;
4.	iv. not make any alterations to the Intellectual Property;
5.	v. not use the Jle mega mart brand name or any derivative of the words comprising the Jle mega mart brand name, in the Distributor’s business, or personal domain names;
6.	vi. stop using the Intellectual Property upon the termination of this Agreement or Distributorship or at the immediate request of Jle mega mart;
7.	vii. not modify the design, appearance and attributed of any products or services, packaging, promotion or marketing materials;
8.	viii. not register or attempt to register a business name or company name that contains the word “Jle mega mart” or any combination of words that indicates a connection with or is similar to Jle mega mart.
9.	ix. not consent or oppose or assist any other person to contest or oppose any application for registration of the Intellectual Property as trademarks or as business or company names.
10.	x. not reproduce, in whole or in part, any printed material or audio or visual recordings that have been produced by Jle mega mart unless given prior written authorization to do so by Jle mega mart. These materials form part of the Intellectual Property whether registered or unregistered and are considered proprietary to Jle mega mart.
11.	xi. not publish Website materials in any media, personal and/or any other website.
12.	xii. not sell, sub-license and /or otherwise commercialize any website material other than the products that shall be purchased through such website.
13.	xiii. not publicly display, show, present any website material.
14.	xiv. not use the Website in any way that is, or may be, damaging to this website.
15.	xv. not use the website in any way that impacts user access to this website.
16.	xvi. not use this website contrary to applicable law and regulations, or in a way that causes, or may cause, harm to the website, or to any person or business entity.
17.	xvii. not engage in any data mining, data harvesting, data extracting or any other similar activity in relation to this website, or while using this website.
18.	xviii. not use this website to engage in any advertising or marketing.
19.	xix. not systematically retrieve data or other content from the Website to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission of Jle mega mart.
20.	xx. not make any unauthorized use of the Website, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email, or creating Direct Seller accounts by automated means or under false pretenses.
21.	xxi. not engage in unauthorized framing of or linking to Jle mega mart’s Website
22.	xxii. not interfere with, disrupt, or create an undue burden on the Website or the networks or services connected to the Website.
23.	xxiii. not decipher, decompile, disassemble, or reverse engineer any of the software comprising or in any way making up a part of the Website.
24.	xxiv. not upload or transmit or attempt to upload or to transmit viruses, Trojan horses, or other material, that interferes with any party’s uninterrupted use and enjoyment of the Website or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Website.</p>
<h1>I. Payments:</h1>
<p>You hereby agree and understand that you will have to pay such charges as are mentioned on the Website for the concerned products & services via the payment mode provided on the Website subsequent to which the Order shall be confirmed. You agree and acknowledge that the payment procedure may call for and require additional verification of or information and you hereby undertake to provide complete, correct and proper information.
All the users of the Website are hereby informed that Jle mega mart uses third party payment providers to receive payments from such users. Jle mega mart shall not in any way be responsible for delays or erroneous transaction execution or cancellation of Orders due to payment issues.
Jle mega mart takes utmost care to work with third party payment providers but does not control their systems, processes, technology and work flows and therefore cannot be held responsible for any fault at the end of payment providers.
The Website user understands that the payment facility provided by Jle mega mart is neither a banking nor financial service but that Jle mega mart is merely a facilitator in providing an electronic, automated online electronic payment for transactions on the Website using existing authorized banking infrastructure and payment gateway networks. By providing payment facility Jle mega mart is neither acting as a trustee nor acting in a fiduciary capacity with respect to the transaction or the transaction price.
Website user who shall be making payments for the products or services using Jle mega mart’s Website, would be making payments to the entities mentioned as per the link mentioned in the tab named SHOPPING MALL.</p>
<h1>J. Use of Vendors:</h1>
<p>We may employ vendors to perform functions on our behalf, such as fulfilling orders, delivering packages, processing payments, and providing customer service. These vendors are under a contractual obligation to use confidential data received from Jle mega mart only for purposes that fall within the functions for which they were hired.
We may disclose information that we collect about you when we have reason to believe that this is necessary to identify, contact or bring legal action against persons or entities that may be harming you, us or others. We may also disclose information when we believe the law requires it.</p>
<h1>K. Data Transmission:</h1>
<p>We take reasonable steps to ensure that the personal information we collect about you remains accurate, timely and secure. Unfortunately, no data transmission over the Internet can be guaranteed to be 100% secure and while we strive to protect your personal information, we cannot guarantee or warrant its complete security. We shall not be responsible for harm that you or any person may suffer as a result of a breach of confidentiality in respect to your use of the Website or any information you transmit to the Website.
When you use Jle mega mart’s Website, you agree and understand that you are communicating with Jle mega mart through electronic means and you give your explicit consent to receive communications via electronic means from Jle mega mart periodically and as and when required. It is however to be noted that Jle mega mart may communicate with you by any of the means such as SMS, Email, Website Notifications, alerts or by such other mode of communication, electronic or otherwise.
You specifically agree that Jle mega mart shall not be held responsible for unauthorized access to or alteration of your transmissions or data, any material or data sent or received or not sent or not received. Further, Jle mega mart will make best efforts to safeguard the confidentiality of your personally identifiable information available with it, but transmissions made by means of the internet cannot be guaranteed or made absolutely secure. By using this Website, you agree that Jle mega mart shall not be liable for disclosure of your information due to errors in transmission or unauthorized acts of third parties. Without prejudice to the foregoing you agree that Jle mega mart shall not be held liable or responsible for 'phishing attacks' or such other similar attacks on you.</p>
<h1>L. Use of Cookies:</h1>
<p>Cookies are small pieces of information that are stored on computer hard drives. We may use cookies to recognize you when you return to the Website in order to provide you with a better user experience. We may allow third parties to use cookies on the Website.
We do not control the use or contents of third-party cookies. If you elect to block cookies, please note that you may not be able to take full advantage of the features and functions of the Website.
You may accept or decline the cookies when you access the Website. It is your responsibility to set your browser to alert you to accept or to reject cookies.</p>
<h1>M. Transfer of information:</h1>
<p>You hereby acknowledge & accept that the information you provide to us or that we obtain as a result of your use of the Website may be collected in your country and subsequently transferred to another country in accordance with applicable laws. If you do not want to disclose your personal information to us, please do not submit it. This does mean that in some cases, we may not be able to provide you the service you have requested. The use of this Website & the provision of information from your side demonstrates your consent to the processing of information as described in these Terms.</p>
<h1>N. Third Party links:</h1>
<p>The Website may contain links to web sites operated and maintained by third parties over which we have absolutely no control. Any information you provide to third party websites will be governed under the terms of each websites’ privacy policy and we encourage you to investigate and ask questions before disclosing any information to the operators of third-party websites.
Jle mega mart does not regularly review and makes no warranty or representation regarding materials posted, or Services or services offered, on the sites to which this Website may be linked. Jle mega mart cannot be held responsible for any deficiency in services of/by such third-party websites.
We have no responsibility or liability whatsoever for the content, actions or policies of third-party websites. Any decision to view the contents of any linked site is solely the responsibility of the Website user and is made at his/her/its own risk.
Additionally, any references on the Website to any names, marks, logos, products or services of third parties or hypertext links to third party sites or any other information that may be provided does not in any way constitute or imply any endorsement, sponsorship or recommendation of the third party, information, product or service or any association and relationship between Jle mega mart and those third parties.</p>
<h1>O. Limitation of liability:</h1>
<p>In no event shall Jle mega mart, nor any of its officers, directors and employees, be liable to you for anything arising out of or in any way connected with your use of this website, whether such liability is under contract, tort or otherwise, and Jle mega mart , including its officers, directors and employees shall not be liable for any indirect, consequential or special liability arising out of or in any way related to your use of this Website.
Neither Jle mega mart nor any of its officers, directors and employees shall be liable for any damages of any kind whatsoever including but not limited to direct, indirect, incidental, punitive, exemplary and consequential damages, damages for loss of use, data or profits, or other intangible losses, which may arise or are arising from the use of this Website or any of the information, software, services and related graphics contained within the Website or any of the Services offered, regardless of whether such damages are based on contract, tort, negligence, strict liability or otherwise.</p>
<h1>P. Breach of the Terms of Use: </h1>
<p>Jle mega mart reserves the right to temporarily/indefinitely suspend or terminate or block Distributorship and/or refuse to provide access to Jle mega mart’s Website without any prior intimation in the following circumstances:
• In case of breach of the Terms of Use or any other rules and policies as displayed on Jle mega mart’s Website;
• In case Jle mega mart is unable to verify or authenticate the information that has been furnished on its Website by the User;
• In such circumstances wherein Jle mega mart is of the opinion that there is a violation of any law(s) in force.
Jle mega mart reserves the right, in its sole discretion, to suspend or cancel any service at any time if a problem hampers or corrupts the security, or impedes the proper administration of such service.
The Website user willing to use Jle mega mart’s Website also agrees that any breach of these Terms of Use or any other rules or policies (as amended from time to time) as displayed on Jle mega mart’s Website will constitute an unlawful and unfair business practice and will cause irreparable harm to Jle mega mart, for which monetary damages would normally be inadequate. In case payment of monetary damages is deemed adequate remedy in Jle mega mart 's opinion, the Website user consents to pay the same to Jle mega mart, which shall not however prevent the obtaining of any injunctive or equitable relief that Jle mega mart deems necessary or appropriate in such circumstances. These remedies shall be in addition to any other remedies Jle mega mart may have in law or in equity.
If Jle mega mart initiates any legal action as a result of any breach of these Terms of Use or any other rules or policy, Jle mega mart shall also be entitled to recover all reasonable attorneys' fees and costs of such action, in addition to any other relief granted to Jle mega mart.</p>
<h1>Q. Indemnification:</h1>
<p>The Website user shall indemnify, defend and hold harmless Jle mega mart and its officers, directors, employees, contractors, agents, licensors, service providers, subcontractors and suppliers from and against any and all losses (including consequential loss), liabilities (including taxation liabilities), expenses, damages and costs, including reasonable attorneys' fees and court costs, proceeding or demand of any nature howsoever arising, whether present or future, fixed or uncertain, actual or contingent, known or unknown arising or resulting from any breach of these Terms of Use or due to any unlawful conduct committed by the Website user including a breach of Intellectual Property Rights of third parties.</p>
<h1>R. Force Majeure:</h1>
<p>The term force majeure shall include, but not be limited to fires, floods, lightening, disease, acts of God or the public enemy, embargoes, strikes, lockouts, wars (declared or undeclared), riots, civil commotion, interference by civil or military authorities, terrorist acts, Government actions, order(s) or request (s), including (without limitation) certification, clearance or other document, or any other cause or contingency beyond the control of Jle mega mart in any of the aforesaid events.
Jle mega mart shall not be liable for failure to perform or any delay in performance of services when and to extent that such failure or delay is due to force majeure.</p>
<h1>S. Governing law & Jurisdiction:</h1>
<p>These Terms, any dispute or claim arising out of or in connection with it or its subject matter, existence, negotiation, validity, termination or enforceability and all transactions entered into on or through Jle mega mart’s Website shall be interpreted, construed and governed by the laws of India which shall be applicable to these Terms without regard to principles of conflict of laws.
The Website User also agrees that all claims, differences and disputes arising under or in connection with or in relation hereto the Website, the terms or any transactions entered into on or through the Website or the relationship between the Website User & Jle mega mart shall be subject to the exclusive jurisdiction of the courts at Delhi and the Website user hereby accepts the jurisdiction of such courts.</p>
<h1>T. Severance:</h1>
<p>If any provision (or part of a provision) of these Terms is or becomes invalid, illegal or unenforceable, it shall be deemed modified to the minimum extent necessary to make it valid, legal and enforceable. If such modification is not possible, the relevant provision (or part of a provision) shall be deemed deleted. Any modification to or deletion of a provision (or part of a provision) under this clause shall not affect the legality, validity and enforceability of the rest of the Terms.</p>
<h1>U. Headings:</h1>
<p>Headings of the sections of these Terms of Use are inserted for convenience reasons only and shall not affect in any way the substantive meaning or interpretation of the contents of the sections.</p>

   
    <footer className="position-relative" id="footer-main">
        <div className="footer pt-lg-7 footer-dark bg-dark">
         
            <div className="shape-container shape-line shape-position-top shape-orientation-inverse">
                <svg width="2560px" height="100px" xmlns="http://www.w3.org/2000/svg"  preserveAspectRatio="none" x="0px" y="0px" viewBox="0 0 2560 100"  className="fill-section-secondary">
                    <polygon points="2560 0 2560 100 0 100"></polygon>
                </svg>
            </div>
          
            <div className="container pt-4">
                <div className="row">
                    <div className="col-lg-4 mb-5 mb-lg-0">
                      
                        <a href="index.html">
                            {/* <!-- <img alt="Image placeholder" src="assets/img/brand/logo.png" id="footer-logo"> --> */}
                            <span><h3 style={{color : 'white'}}><span style={{color : '#7ac81e'}}>JLE </span>Megamart</h3></span>
                        </a>
                       
                        <p className="mt-4 text-sm opacity-8 pr-lg-4">
                            JLE is an attempt to give tier 2 city the feel of e-commerce.

                        </p>
                      
                        <ul className="nav mt-4">
                            <li className="nav-item">
                                <a className="nav-link" href="#" target="_blank">
                                    <i className="fab fa-instagram"></i>
                                </a>
                            </li>
                            <li className="nav-item">
                                <a className="nav-link" href="#" target="_blank">
                                    <i className="fab fa-facebook"></i>
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div className="col-lg-2 col-6 col-sm-4 ml-lg-auto mb-5 mb-lg-0">
                       
                    </div>
                    <div className="col-lg-2 col-6 col-sm-4 mb-5 mb-lg-0">

                    </div>
                    <div className="col-lg-2 col-6 col-sm-4 mb-5 mb-lg-0">
                              
                    </div>
                </div>
                <hr className="divider divider-fade divider-dark my-4" />
                <div className="row align-items-center justify-content-md-between pb-4">
                    <div className="col-md-6">
                        <div className="copyright text-sm font-weight-bold text-center text-md-left">
                            &copy; 2022 <a href="#" className="font-weight-bold" target="_blank">JLE Megamart</a>. All rights reserved
                        </div>
                    </div>
                    <div className="col-md-6">
                        <ul className="nav justify-content-center justify-content-md-end mt-3 mt-md-0">
                            <li className="nav-item">
                            <Link className="nav-link" to='/terms-and-conditions'>
                                    Terms
                                </Link>
                            </li>
                            <li className="nav-item">
                            <Link className="nav-link" to="/privacy-policy">
                                    Privacy
                                </Link>
                            </li>
                            <li className="nav-item">
                                <Link className="nav-link" to="/refund">
                                    Refund
                                </Link>
                            </li>
                            <li className="nav-item">
                                <Link className="nav-link" to="/contact-us">
                                    Contact Us
                                </Link>
                            </li>
                            <li className="nav-item">
                                <Link className="nav-link" to="/about-us">
                                    About Us
                                </Link>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
        
                    </>
          )
}

export default TermsAndConditions;